# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genlink < Formula
  desc "Generates the URL link in various formats"
  homepage "https://github.com/michimani/genlink"
  version "0.1.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/michimani/genlink/releases/download/v0.1.3/genlink_0.1.3_darwin_x86_64.tar.gz"
    sha256 "9a4e7ec00e526565578f8b39a5f1d7253bb91b26277d6064b57ff3241d767b75"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/michimani/genlink/releases/download/v0.1.3/genlink_0.1.3_linux_x86_64.tar.gz"
    sha256 "c7ed041d314c16906711bc536ab82a8b170d9c83b7f057bfcfbe1926d9c75d7b"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/michimani/genlink/releases/download/v0.1.3/genlink_0.1.3_linux_arm64.tar.gz"
    sha256 "6afa8842542b8ee55833b5af5b9b3b7542b102274c1fe9bfd31408451555dd1f"
  end

  def install
    bin.install "genlink"
  end
end
