# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genlink < Formula
  desc "Generates the URL link in various formats"
  homepage "https://github.com/michimani/genlink"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/michimani/genlink/releases/download/v0.1.1/genlink_0.1.1_darwin_x86_64.tar.gz"
    sha256 "d2869aa94b13e0c4baed51515e0eeb836bd19d6c9f87797bb0d87bba2bf93a30"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/michimani/genlink/releases/download/v0.1.1/genlink_0.1.1_linux_x86_64.tar.gz"
    sha256 "f3550734620ae4d3d1c8c96353bdd1f2ba364d283ad8ad6e1a51b4ce54dd11bc"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/michimani/genlink/releases/download/v0.1.1/genlink_0.1.1_linux_arm64.tar.gz"
    sha256 "ac5b2f1268ac51002069c395c2e3e6e906357552ea44aa127445cf8ff387385b"
  end

  def install
    bin.install "genlink"
  end
end
